### PR TITLE
configurable buffering writer time

### PR DESCRIPTION
**Pull request by toarm**

### CODE REVIEW

**Review by pavelpenchev — APPROVED** [review]
Looks good, what's the use case

**Comment by toarm** [comment]
> Looks good, what's the use case

we just want to see if we can reduce the amount of request by increasing the waiting time

**Comment by pavelpenchev** [comment]
But potentially lose events if the browser tab is closed? or you've attached an on close listener?

**Comment by toarm** [comment]
> But potentially lose events if the browser tab is closed? or you've attached an on close listener?

yep, you have to find the balance and it doesnt hurt if you are able to change that parameter

**Pull request merged**
